os: linux
sudo: false
language: go

go:
  - 1.7.6
  - 1.8.3
  - 1.9
  - master

matrix:
  allow_failures:
    - go: master

branches:
  only:
    - master

notifications:
  email:
    on_success: always
