os: linux
sudo: false
language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

matrix:
  allow_failures:
    - go: master

branches:
  only:
    - master

notifications:
  email:
    on_success: always
